
services:
  postgres-clientes:
    image: postgres:16
    container_name: postgres-clientes
    environment:
      POSTGRES_DB: clientedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata-clientes:/var/lib/postgresql/data

  postgres-produtos:
    image: postgres:16
    container_name: postgres-produtos
    environment:
      POSTGRES_DB: produtodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata-produtos:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-clientes
      - postgres-produtos

  cliente-service:
    build: ./cliente-service
    container_name: cliente-service
    depends_on:
      - postgres-clientes
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-clientes:5432/clientedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8081"

  produto-service:
    build: ./produto-service
    container_name: produto-service
    depends_on:
      - postgres-produtos
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-produtos:5432/produtodb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8082:8082"

volumes:
  pgdata-clientes:
  pgdata-produtos:
