version: "3.8"

services:
  postgres-clientes:
    image: postgres
    container_name: postgres-clientes
    environment:
      POSTGRES_DB: clientedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - pgdata-clientes:/var/lib/postgresql/data

  postgres-produtos:
    image: postgres
    container_name: postgres-produtos
    environment:
      POSTGRES_DB: produtodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    ports:
      - "5433:5432"
    volumes:
      - pgdata-produtos:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-clientes

volumes:
  pgdata-clientes:
  pgdata-produtos:
